AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: provided.al2
    Handler: bootstrap
    Architectures:
      - x86_64

Resources:
  HelloGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Sample

  HelloFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: hello/
      Events:
        Api:
          Type: Api 
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref HelloGateway
