AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: go1.x
    Handler: main

Resources:
  HelloGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Sample

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello/
      Events:
        Api:
          Type: Api 
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref HelloGateway
